### ISSUE TITLE
Switching to an empty workspace is broken after v3.1.0

### ISSUE THREAD

**Issue by tkapias** [roosta/i3wsr#41]
OS : Debian Testing
WM : i3wm, single display

I had to downgrade to v3.0.0, because with v3.1.0 or v3.1.1 I could not switch to an empty workspace anymore.

Using `mod+2` from workspace 1 just gives a flicker on the screen.

Also, I use a script to toggle some windows from the scratchpad to the current workspace and back, but after v3.1.0 the toggling does not respect the current workspace and can send me to another one randomly.

My i3wsr config:

``` toml
[general]
display_property = "instance"
separator = "  "
empty_label = ""

[options]
no_icon_names = true
no_names = false
remove_duplicates = true

[aliases.class]
"firefox-esr" = "Firefox"

[icons]
Firefox = "󰈹"
KeePassXC = ""
mpv = "󰐍"
Pcmanfm = ""
Qalculate-gtk = "󰃬"
scrcpy = "󰓷"
Kitty-Quake = ""
```
